'use client';

import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'te' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  getTranslation: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, any>> = {
  en: {
    keyMapping: {
        dashboard: 'Dashboard',
        encyclopedia: 'Encyclopedia',
        preventiveCare: 'Preventive Care',
        fieldLogbook: 'Field Logbook',
        recommendations: 'Crop Recommendations',
        profitCalculator: 'Profit Calculator',
    },
    dashboard: {
      quickGuide: 'Quick Guide',
      guideStep1: '1. Upload a clear photo of the affected crop.',
      guideStep2: '2. Let our AI analyze for diseases or pests.',
      guideStep3: '3. Receive instant organic treatment advice.',
      dragAndDrop: 'Drag & drop an image here',
      or: 'or',
      browseFiles: 'Browse files',
      analyzing: 'Analyzing...',
      analyzeCrop: 'Analyze Crop',
      analysisReport: 'Analysis Report',
      newAnalysis: 'New Analysis',
      aiAnalysis: 'AI Analysis',
      treatmentSuggestions: 'Treatment Suggestions',
      localWeather: 'Local Weather',
      selectCity: 'Select a city',
      weatherError: 'Could not fetch weather data.',
      weatherDescription: 'Real-time conditions for your crops',
      sunny: 'Sunny',
      humidity: 'Humidity',
      uvIndex: 'UV Index',
      high: 'High',
      highAlert: 'High Alert!',
      alertDescription: 'High humidity and temperature increase the risk of Powdery Mildew. Consider preventive spraying.',
      analysisFailed: 'Analysis Failed',
      analysisError: 'Could not analyze image. Please try again.'
    },
    encyclopedia: {
      title: 'Encyclopedia',
      symptoms: 'Symptoms',
      prevention: 'Prevention',
      organicTreatment: 'Organic Treatment',
      searchPlaceholder: 'Search for any disease, pest, or topic...',
      searchButton: 'Search',
      clearSearch: 'Clear',
      notFound: 'No Results Found',
      searchErrorTitle: 'Search Failed',
      searchErrorDescription: 'Could not perform search. Please try again.',
    },
    preventiveCare: {
      title: 'Preventive Care',
      pageTitle: 'Crop Care Guide',
      pageDescription: 'Proactive tips to keep your crops healthy and thriving.',
      searchPlaceholder: 'Search for a crop to get care tips...',
      searchErrorTitle: 'Search Failed',
      searchErrorDescription: 'Could not fetch care tips. Please try again.',
    },
    logbook: {
      title: 'Field Logbook',
      addLog: 'Add New Log',
      addLogDescription: 'Record a new activity for your field.',
      activity: 'Activity',
      activityPlaceholder: 'e.g., Applied neem oil',
      notes: 'Notes (optional)',
      notesPlaceholder: 'e.g., On the north field',
      addLogButton: 'Add Log',
      recentActivities: 'Recent Activities',
      noActivities: 'No activities logged yet.'
    },
    chatbot: {
      title: 'AI Assistant',
      placeholder: 'Ask me anything about farming...',
    },
    recommendations: {
        title: 'Farm Data',
        description: 'The more details you provide, the better the recommendation.',
        location: 'Location',
        locationPlaceholder: 'e.g., Central Valley, California',
        locationDescription: 'City, State, or Region.',
        soilType: 'Soil Type',
        soilTypePlaceholder: 'Select a soil type',
        soilTypeDescription: 'Predominant soil type in your field.',
        pastCropRotation: 'Past Crop Rotation',
        pastCropRotationPlaceholder: 'e.g., Corn, Soybeans, Fallow',
        pastCropRotationDescription: 'List the crops grown in the last 1-3 seasons.',
        additionalInformation: 'Additional Information',
        additionalInformationPlaceholder: 'e.g., Access to irrigation, specific market demands, etc.',
        additionalInformationDescription: 'Any other details like climate, water access, etc.',
        getRecommendation: 'Get Recommendation',
        resultsTitle: 'Crop Recommendations',
        resultsDescription: 'Based on the data you provided, here are the top crop suggestions.',
        whySuitable: 'Why it\'s suitable',
        plantingSeason: 'Planting Season',
        organicFertilizers: 'Organic Fertilizers',
        errorTitle: 'Failed to Get Recommendations',
        errorDescription: 'An unexpected error occurred. Please try again.',
    },
    profitCalculator: {
        pageTitle: 'Profit Calculator',
        pageDescription: 'Estimate your potential revenue and profit for a crop.',
        inputsTitle: 'Calculation Inputs',
        inputsDescription: 'Enter the details for your crop to calculate the profit.',
        cropName: 'Crop Name',
        acreage: 'Total Acreage',
        yield: 'Yield (kg/acre)',
        marketPrice: 'Market Price (₱/kg)',
        totalCosts: 'Total Costs (₱)',
        calculateButton: 'Calculate Profit',
        waitingTitle: 'Profit Calculation',
        waitingDescription: 'Your profit estimates will appear here after calculation.',
        resultsTitle: 'Profit Analysis',
        resultsDescription: 'Here is a breakdown of your potential profit.',
        totalYield: 'Total Yield',
        totalRevenue: 'Total Revenue',
        profit: 'Estimated Profit',
        profitMargin: 'Profit Margin',
        summaryTitle: 'AI Summary',
        errorTitle: 'Calculation Failed',
        errorDescription: 'Could not calculate profit. Please check your inputs and try again.',
    },
  },
  hi: {
    keyMapping: {
        dashboard: 'डैशबोर्ड',
        encyclopedia: 'विश्वकोश',
        preventiveCare: 'निवारक देखभाल',
        fieldLogbook: 'फील्ड लॉगबुक',
        recommendations: 'फ़सल सिफ़ारिशें',
        profitCalculator: 'लाभ कैलकुलेटर',
    },
    dashboard: {
      quickGuide: 'त्वरित गाइड',
      guideStep1: '1. प्रभावित फसल का एक स्पष्ट फोटो अपलोड करें।',
      guideStep2: '2. हमारे AI को बीमारियों या कीटों का विश्लेषण करने दें।',
      guideStep3: '3. तुरंत जैविक उपचार सलाह प्राप्त करें।',
      dragAndDrop: 'यहां एक छवि खींचें और छोड़ें',
      or: 'या',
      browseFiles: 'फ़ाइलें ब्राउज़ करें',
      analyzing: 'विश्लेषण हो रहा है...',
      analyzeCrop: 'फसल का विश्लेषण करें',
      analysisReport: 'विश्लेषण रिपोर्ट',
      newAnalysis: 'नया विश्लेषण',
      aiAnalysis: 'एआई विश्लेषण',
      treatmentSuggestions: 'उपचार सुझाव',
      localWeather: 'स्थानीय मौसम',
      selectCity: 'एक शहर चुनें',
      weatherError: 'मौसम डेटा प्राप्त नहीं हो सका।',
      weatherDescription: 'आपकी फसलों के लिए वास्तविक समय की स्थितियाँ',
      sunny: 'धूप',
      humidity: 'नमी',
      uvIndex: 'यूवी इंडेक्स',
      high: 'उच्च',
      highAlert: 'उच्च चेतावनी!',
      alertDescription: 'उच्च नमी और तापमान पाउडरी मिल्ड्यू के खतरे को बढ़ाते हैं। निवारक छिड़काव पर विचार करें।',
      analysisFailed: 'विश्लेषण विफल',
      analysisError: 'छवि का विश्लेषण नहीं हो सका। कृपया पुनः प्रयास करें।'
    },
    encyclopedia: {
      title: 'विश्वकोश',
      symptoms: 'लक्षण',
      prevention: 'निवारण',
      organicTreatment: 'जैविक उपचार',
      searchPlaceholder: 'किसी भी बीमारी, कीट या विषय के लिए खोजें...',
      searchButton: 'खोज',
      clearSearch: 'साफ़ करें',
      notFound: 'कोई परिणाम नहीं मिला',
      searchErrorTitle: 'खोज विफल',
      searchErrorDescription: 'खोज नहीं की जा सकी। कृपया पुनः प्रयास करें।',
    },
    preventiveCare: {
      title: 'निवारक देखभाल',
      pageTitle: 'फसल देखभाल गाइड',
      pageDescription: 'आपकी फसलों को स्वस्थ और समृद्ध रखने के लिए सक्रिय सुझाव।',
      searchPlaceholder: 'देखभाल युक्तियों के लिए फसल खोजें...',
      searchErrorTitle: 'खोज विफल',
      searchErrorDescription: 'देखभाल युक्तियाँ प्राप्त नहीं की जा सकीं। कृपया पुनः प्रयास करें।',
    },
    logbook: {
      title: 'फील्ड लॉगबुक',
      addLog: 'नया लॉग जोड़ें',
      addLogDescription: 'अपने क्षेत्र के लिए एक नई गतिविधि रिकॉर्ड करें।',
      activity: 'गतिविधि',
      activityPlaceholder: 'उदा., नीम का तेल लगाया',
      notes: 'नोट्स (वैकल्पिक)',
      notesPlaceholder: 'उदा., उत्तरी क्षेत्र पर',
      addLogButton: 'लॉग जोड़ें',
      recentActivities: 'हाल की गतिविधियाँ',
      noActivities: 'अभी तक कोई गतिविधि लॉग नहीं की गई है।'
    },
    chatbot: {
      title: 'एआई सहायक',
      placeholder: 'खेती के बारे में कुछ भी पूछें...',
    },
    recommendations: {
        title: 'खेत का डेटा',
        description: 'आप जितने अधिक विवरण प्रदान करेंगे, सिफारिश उतनी ही बेहतर होगी।',
        location: 'स्थान',
        locationPlaceholder: 'उदा., सेंट्रल वैली, कैलिफोर्निया',
        locationDescription: 'शहर, राज्य, या क्षेत्र।',
        soilType: 'मिट्टी का प्रकार',
        soilTypePlaceholder: 'मिट्टी का प्रकार चुनें',
        soilTypeDescription: 'आपके खेत में प्रमुख मिट्टी का प्रकार।',
        pastCropRotation: 'पिछला फसल चक्र',
        pastCropRotationPlaceholder: 'उदा., मक्का, सोयाबीन, परती',
        pastCropRotationDescription: 'पिछले 1-3 सत्रों में उगाई गई फसलों की सूची बनाएं।',
        additionalInformation: 'अतिरिक्त जानकारी',
        additionalInformationPlaceholder: 'उदा., सिंचाई तक पहुंच, विशिष्ट बाजार की मांग, आदि।',
        additionalInformationDescription: 'जलवायु, पानी तक पहुंच, आदि जैसे कोई अन्य विवरण।',
        getRecommendation: 'सिफारिश प्राप्त करें',
        resultsTitle: 'फसल सिफारिशें',
        resultsDescription: 'आपके द्वारा प्रदान किए गए डेटा के आधार पर, यहां शीर्ष फसल सुझाव दिए गए हैं।',
        whySuitable: 'यह उपयुक्त क्यों है',
        plantingSeason: 'रोपण का मौसम',
        organicFertilizers: 'जैविक उर्वरक',
        errorTitle: 'सिफारिशें प्राप्त करने में विफल',
        errorDescription: 'एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।',
    },
    profitCalculator: {
        pageTitle: 'लाभ कैलकुलेटर',
        pageDescription: 'एक फसल के लिए अपनी संभावित राजस्व और लाभ का अनुमान लगाएं।',
        inputsTitle: 'गणना इनपुट',
        inputsDescription: 'लाभ की गणना के लिए अपनी फसल का विवरण दर्ज करें।',
        cropName: 'फसल का नाम',
        acreage: 'कुल एकड़',
        yield: 'उपज (किलो/एकड़)',
        marketPrice: 'बाजार मूल्य (₱/किलो)',
        totalCosts: 'कुल लागत (₱)',
        calculateButton: 'लाभ की गणना करें',
        waitingTitle: 'लाभ गणना',
        waitingDescription: 'गणना के बाद आपके लाभ का अनुमान यहां दिखाई देगा।',
        resultsTitle: 'लाभ विश्लेषण',
        resultsDescription: 'यहाँ आपके संभावित लाभ का विवरण है।',
        totalYield: 'कुल उपज',
        totalRevenue: 'कुल राजस्व',
        profit: 'अनुमानित लाभ',
        profitMargin: 'लाभ मार्जिन',
        summaryTitle: 'AI सारांश',
        errorTitle: 'गणना विफल',
        errorDescription: 'लाभ की गणना नहीं हो सकी। कृपया अपने इनपुट की जांच करें और पुनः प्रयास करें।',
    },
  },
  te: {
    keyMapping: {
        dashboard: 'డాష్‌బోర్డ్',
        encyclopedia: 'ఎన్సైక్లోపీడియా',
        preventiveCare: 'నివారణ సంరక్షణ',
        fieldLogbook: 'ఫీల్డ్ లాగ్‌బుక్',
        recommendations: 'పంట సిఫార్సులు',
        profitCalculator: 'లాభాల కాలిక్యులేటర్',
    },
    dashboard: {
      quickGuide: 'త్వరిత గైడ్',
      guideStep1: '1. ప్రభావిత పంట యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి.',
      guideStep2: '2. మా AI వ్యాధులు లేదా తెగుళ్ళను విశ్లేషించనివ్వండి.',
      guideStep3: '3. తక్షణ సేంద్రీయ చికిత్స సలహాలను స్వీకరించండి.',
      dragAndDrop: 'ఇక్కడ చిత్రాన్ని లాగండి మరియు వదలండి',
      or: 'లేదా',
      browseFiles: 'ఫైల్‌లను బ్రౌజ్ చేయండి',
      analyzing: 'విశ్లేషిస్తోంది...',
      analyzeCrop: 'పంటను విశ్లేషించండి',
      analysisReport: 'విశ్లేషణ నివేదిక',
      newAnalysis: 'కొత్త విశ్లేషణ',
      aiAnalysis: 'AI విశ్లేషణ',
      treatmentSuggestions: 'చికిత్స సూచనలు',
      localWeather: 'స్థానిక వాతావరణం',
      selectCity: 'ఒక నగరాన్ని ఎంచుకోండి',
      weatherError: 'వాతావరణ డేటాను పొందడం సాధ్యం కాలేదు.',
      weatherDescription: 'మీ పంటల కోసం నిజ-సమయ పరిస్థితులు',
      sunny: 'ఎండ',
      humidity: 'తేమ',
      uvIndex: 'UV సూచిక',
      high: 'అధిక',
      highAlert: 'అధిక హెచ్చరిక!',
      alertDescription: 'అధిక తేమ మరియు ఉష్ణోగ్రత బూజు తెగులు ప్రమాదాన్ని పెంచుతాయి. నివారణ స్ప్రేయింగ్ పరిగణించండి.',
      analysisFailed: 'విశ్లేషణ విఫలమైంది',
      analysisError: 'చిత్రాన్ని విశ్లేషించడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.'
    },
    encyclopedia: {
      title: 'ఎన్సైక్లోపీడియా',
      symptoms: 'లక్షణాలు',
      prevention: 'నివారణ',
      organicTreatment: 'సేంద్రీయ చికిత్స',
      searchPlaceholder: 'ఏదైనా వ్యాధి, తెగులు లేదా అంశం కోసం శోధించండి...',
      searchButton: 'శోధన',
      clearSearch: 'క్లియర్ చేయండి',
      notFound: 'ఫలితాలు కనుగొనబడలేదు',
      searchErrorTitle: 'శోధన విఫలమైంది',
      searchErrorDescription: 'శోధన చేయడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    },
    preventiveCare: {
      title: 'నివారణ సంరక్షణ',
      pageTitle: 'పంట సంరక్షణ గైడ్',
      pageDescription: 'మీ పంటలను ఆరోగ్యంగా మరియు అభివృద్ధి చెందడానికి చురుకైన చిట్కాలు.',
      searchPlaceholder: 'సంరక్షణ చిట్కాలను పొందడానికి ఒక పంట కోసం శోధించండి...',
      searchErrorTitle: 'శోధన విఫలమైంది',
      searchErrorDescription: 'సంరక్షణ చిట్కాలను పొందడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    },
    logbook: {
      title: 'ఫీల్డ్ లాగ్‌బుక్',
      addLog: 'కొత్త లాగ్ జోడించండి',
      addLogDescription: 'మీ ఫీల్డ్ కోసం కొత్త కార్యాచరణను రికార్డ్ చేయండి.',
      activity: 'కార్యాచరణ',
      activityPlaceholder: 'ఉదా., వేప నూనె పూయబడింది',
      notes: 'గమనికలు (ఐచ్ఛికం)',
      notesPlaceholder: 'ఉదా., ఉత్తర క్షేత్రంలో',
      addLogButton: 'లాగ్ జోడించండి',
      recentActivities: 'ఇటీవలి కార్యకలాపాలు',
      noActivities: 'ఇంకా కార్యకలాపాలు లాగ్ చేయబడలేదు.'
    },
    chatbot: {
      title: 'AI సహాయకుడు',
      placeholder: 'వ్యవసాయం గురించి ఏదైనా అడగండి...',
    },
    recommendations: {
        title: 'పొలం డేటా',
        description: 'మీరు ఎంత ఎక్కువ వివరాలు అందిస్తే, సిఫార్సు అంత మెరుగ్గా ఉంటుంది.',
        location: 'ప్రదేశం',
        locationPlaceholder: 'ఉదా., సెంట్రల్ వ్యాలీ, కాలిఫోర్నియా',
        locationDescription: 'నగరం, రాష్ట్రం లేదా ప్రాంతం.',
        soilType: 'నేల రకం',
        soilTypePlaceholder: 'నేల రకాన్ని ఎంచుకోండి',
        soilTypeDescription: 'మీ పొలంలో ప్రధాన నేల రకం.',
        pastCropRotation: 'గత పంట మార్పిడి',
        pastCropRotationPlaceholder: 'ఉదా., మొక్కజొన్న, సోయాబీన్స్, బీడు',
        pastCropRotationDescription: 'గత 1-3 సీజన్లలో పండించిన పంటలను జాబితా చేయండి.',
        additionalInformation: 'అదనపు సమాచారం',
        additionalInformationPlaceholder: 'ఉదా., నీటిపారుదల సౌకర్యం, నిర్దిష్ట మార్కెట్ డిమాండ్లు మొదలైనవి.',
        additionalInformationDescription: 'వాతావరణం, నీటి సౌకర్యం వంటి ఇతర వివరాలు.',
        getRecommendation: 'సిఫార్సు పొందండి',
        resultsTitle: 'పంట సిఫార్సులు',
        resultsDescription: 'మీరు అందించిన డేటా ఆధారంగా, ఇక్కడ అగ్ర పంట సూచనలు ఉన్నాయి.',
        whySuitable: 'ఇది ఎందుకు అనువైనది',
        plantingSeason: 'నాటడం కాలం',
        organicFertilizers: 'సేంద్రీయ ఎరువులు',
        errorTitle: 'సిఫార్సులను పొందడంలో విఫలమైంది',
        errorDescription: 'ఒక ఊహించని లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    },
    profitCalculator: {
        pageTitle: 'లాభాల కాలిక్యులేటర్',
        pageDescription: 'ఒక పంట కోసం మీ సంభావ్య ఆదాయం మరియు లాభాన్ని అంచనా వేయండి.',
        inputsTitle: 'గణన ఇన్‌పుట్‌లు',
        inputsDescription: 'లాభాన్ని గణించడానికి మీ పంట వివరాలను నమోదు చేయండి.',
        cropName: 'పంట పేరు',
        acreage: 'మొత్తం ఎకరేజ్',
        yield: 'దిగుబడి (కిలోలు/ఎకరా)',
        marketPrice: 'మార్కెట్ ధర (₱/కిలో)',
        totalCosts: 'మొత్తం ఖర్చులు (₱)',
        calculateButton: 'లాభాన్ని గణించండి',
        waitingTitle: 'లాభాల గణన',
        waitingDescription: 'గణన తర్వాత మీ లాభాల అంచనాలు ఇక్కడ కనిపిస్తాయి.',
        resultsTitle: 'లాభాల విశ్లేషణ',
        resultsDescription: 'మీ సంభావ్య లాభం యొక్క విచ్ఛిన్నం ఇక్కడ ఉంది.',
        totalYield: 'మొత్తం దిగుబడి',
        totalRevenue: 'మొత్తం ఆదాయం',
        profit: 'అంచనా వేసిన లాభం',
        profitMargin: 'లాభాల మార్జిన్',
        summaryTitle: 'AI సారాంశం',
        errorTitle: 'గణన విఫలమైంది',
        errorDescription: 'లాభాన్ని గణించడంలో విఫలమైంది. దయచేసి మీ ఇన్‌పుట్‌లను తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి.',
    },
  },
  ta: {
    keyMapping: {
        dashboard: 'முதன்மைப் பக்கம்',
        encyclopedia: 'களஞ்சியம்',
        preventiveCare: 'தடுப்பு பராமரிப்பு',
        fieldLogbook: 'புல பதிவு புத்தகம்',
        recommendations: 'பயிர் பரிந்துரைகள்',
        profitCalculator: 'இலாப கால்குலேட்டர்',
    },
    dashboard: {
      quickGuide: 'விரைவு வழிகாட்டி',
      guideStep1: '1. பாதிக்கப்பட்ட பயிரின் தெளிவான புகைப்படத்தைப் பதிவேற்றவும்.',
      guideStep2: '2. எங்கள் AI நோய்கள் அல்லது பூச்சிகளை பகுப்பாய்வு செய்யட்டும்.',
      guideStep3: '3. உடனடி கரிம சிகிச்சை ஆலோசனையைப் பெறுங்கள்.',
      dragAndDrop: 'படத்தை இங்கே இழுத்து விடவும்',
      or: 'அல்லது',
      browseFiles: 'கோப்புகளை உலாவுக',
      analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
      analyzeCrop: 'பயிரை பகுப்பாய்வு செய்',
      analysisReport: 'பகுப்பாய்வு அறிக்கை',
      newAnalysis: 'புதிய பகுப்பாய்வு',
      aiAnalysis: 'AI பகுப்பாய்வு',
      treatmentSuggestions: 'சிகிச்சை பரிந்துரைகள்',
      localWeather: 'உள்ளூர் வானிலை',
      selectCity: 'ஒரு நகரத்தைத் தேர்ந்தெடுக்கவும்',
      weatherError: 'வானிலை தரவைப் பெற முடியவில்லை.',
      weatherDescription: 'உங்கள் பயிர்களுக்கான நிகழ்நேர நிலைமைகள்',
      sunny: 'வெயில்',
      humidity: 'ஈரப்பதம்',
      uvIndex: 'புற ஊதா குறியீடு',
      high: 'அதிகம்',
      highAlert: 'உயர் எச்சரிக்கை!',
      alertDescription: 'அதிக ஈரப்பதம் மற்றும் வெப்பநிலை சாம்பல் நோய் அபாயத்தை αυξάνει. தடுப்பு தெளிப்பைக் கவனியுங்கள்.',
      analysisFailed: 'பகுப்பாய்வு தோல்வியுற்றது',
      analysisError: 'படத்தை பகுப்பாய்வு செய்ய முடியவில்லை. ദയവായി വീണ്ടും ശ്രമിക്കുക.'
    },
    encyclopedia: {
      title: 'களஞ்சியம்',
      symptoms: 'அறிகுறிகள்',
      prevention: 'தடுப்பு',
      organicTreatment: 'கரிம சிகிச்சை',
      searchPlaceholder: 'எந்தவொரு நோய், பூச்சி அல்லது தலைப்புக்கு தேடவும்...',
      searchButton: 'தேடல்',
      clearSearch: 'அழி',
      notFound: 'முடிவுகள் எதுவும் இல்லை',
      searchErrorTitle: 'தேடல் தோல்வியுற்றது',
      searchErrorDescription: 'தேடல் செய்ய முடியவில்லை. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    },
    preventiveCare: {
      title: 'தடுப்பு பராமரிப்பு',
      pageTitle: 'பயிர் பராமரிப்பு வழிகாட்டி',
      pageDescription: 'உங்கள் பயிர்களை ஆரோக்கியமாகவும் செழிப்பாகவும் வைத்திருக்க செயல்திட்ட குறிப்புகள்.',
      searchPlaceholder: 'பராமரிப்பு குறிப்புகளைப் பெற ஒரு பயிரைத் தேடுங்கள்...',
      searchErrorTitle: 'தேடல் தோல்வியுற்றது',
      searchErrorDescription: 'பராமரிப்பு குறிப்புகளைப் பெற முடியவில்லை. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    },
    logbook: {
      title: 'புல பதிவு புத்தகம்',
      addLog: 'புதிய பதிவைச் சேர்',
      addLogDescription: 'உங்கள் புலத்திற்கான புதிய செயல்பாட்டைப் பதிவுசெய்க.',
      activity: 'செயல்பாடு',
      activityPlaceholder: 'எ.கா., வேப்ப எண்ணெய் பயன்படுத்தப்பட்டது',
      notes: 'குறிப்புகள் (விருப்பத்தேர்வு)',
      notesPlaceholder: 'எ.கா., வடக்கு புலத்தில்',
      addLogButton: 'பதிவைச் சேர்',
      recentActivities: 'சமீபத்திய செயல்பாடுகள்',
      noActivities: 'செயல்பாடுகள் எதுவும்まだ பதிவு செய்யப்படவில்லை.'
    },
    chatbot: {
        title: 'AI உதவியாளர்',
        placeholder: 'விவசாயம் பற்றி எதுவும் கேளுங்கள்...',
    },
    recommendations: {
        title: 'பண்ணை தரவு',
        description: 'நீங்கள் எவ்வளவு ఎక్కువ వివరాలు అందిస్తే, సిఫార్సు అంత మెరుగ్గా ఉంటుంది.',
        location: 'இடம்',
        locationPlaceholder: 'எ.கா., சென்ட்ரல் வேலி, கலிபோர்னியா',
        locationDescription: 'நகரம், மாநிலம், அல்லது பகுதி.',
        soilType: 'மண் வகை',
        soilTypePlaceholder: 'மண் வகையைத் தேர்ந்தெடுக்கவும்',
        soilTypeDescription: 'உங்கள் வயலில் உள்ள முக்கிய மண் வகை.',
        pastCropRotation: 'கடந்த பயிர் சுழற்சி',
        pastCropRotationPlaceholder: 'எ.கா., மக்காச்சோளம், சோயாபீன்ஸ், தரிசு',
        pastCropRotationDescription: 'கடந்த 1-3 பருவங்களில் பயிரிடப்பட்ட பயிர்களைப் பட்டியலிடுங்கள்.',
        additionalInformation: 'கூடுதல் தகவல்',
        additionalInformationPlaceholder: 'எ.கா., நீர்ப்பாசன வசதி, குறிப்பிட்ட சந்தை தேவைகள் போன்றவை.',
        additionalInformationDescription: 'வானிலை, நீர் அணுகல் போன்ற பிற விவரங்கள்.',
        getRecommendation: 'பரிந்துரையைப் பெறுங்கள்',
        resultsTitle: 'பயிர் பரிந்துரைகள்',
        resultsDescription: 'நீங்கள் வழங்கிய தரவுகளின் அடிப்படையில், இங்கே சிறந்த பயிர் பரிந்துரைகள் உள்ளன.',
        whySuitable: 'இது ஏன் பொருத்தமானது',
        plantingSeason: 'நடும் பருவம்',
        organicFertilizers: 'கரிம உரங்கள்',
        errorTitle: 'பரிந்துரைகளைப் பெற முடியவில்லை',
        errorDescription: 'ഒരു അപ്രതീക്ഷിത പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    },
    profitCalculator: {
        pageTitle: 'இலாப கால்குலேட்டர்',
        pageDescription: 'ஒரு பயிருக்கான உங்கள் சாத்தியமான வருவாய் மற்றும் இலாபத்தை மதிப்பிடுங்கள்.',
        inputsTitle: 'கணக்கீட்டு உள்ளீடுகள்',
        inputsDescription: 'இலாபத்தைக் கணக்கிட உங்கள் பயிர் விவரங்களை உள்ளிடவும்.',
        cropName: 'பயிர் பெயர்',
        acreage: 'மொத்த ஏக்கர்',
        yield: 'விளைச்சல் (கிலோ/ஏக்கர்)',
        marketPrice: 'சந்தை விலை (₱/கிலோ)',
        totalCosts: 'மொத்த செலவுகள் (₱)',
        calculateButton: 'இலாபத்தைக் கணக்கிடு',
        waitingTitle: 'இலாபக் கணக்கீடு',
        waitingDescription: 'கணக்கீட்டிற்குப் பிறகு உங்கள் இலாப மதிப்பீடுகள் இங்கே தோன்றும்.',
        resultsTitle: 'இலாபப் பகுப்பாய்வு',
        resultsDescription: 'உங்கள் சாத்தியமான இலாபத்தின் விவரம் இங்கே.',
        totalYield: 'மொத்த விளைச்சல்',
        totalRevenue: 'மொத்த வருவாய்',
        profit: 'மதிப்பிடப்பட்ட இலாபம்',
        profitMargin: 'இலாப வரம்பு',
        summaryTitle: 'AI சுருக்கம்',
        errorTitle: 'கணக்கீடு தோல்வியுற்றது',
        errorDescription: 'இலாபத்தைக் கணக்கிட முடியவில்லை. உங்கள் உள்ளீடுகளைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    },
  },
};


function getNestedTranslation(translations: Record<string, any>, key: string, lang: Language): string {
    const keys = key.split('.');
    let result = translations[lang];
    for (const k of keys) {
        if (result && typeof result === 'object' && k in result) {
            result = result[k];
        } else {
            const enResult = translations['en'];
            let fallbackResult = enResult;
            for (const fk of keys) {
                if (fallbackResult && typeof fallbackResult === 'object' && fk in fallbackResult) {
                    fallbackResult = fallbackResult[fk];
                } else {
                    return key;
                }
            }
            return typeof fallbackResult === 'string' ? fallbackResult : key;
        }
    }
    return typeof result === 'string' ? result : key;
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const getTranslation = useCallback((key: string) => {
    if(!key) return '';
    return getNestedTranslation(translations, key, language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
